version: '3.5'

services:
  frontend:
    build: nebulaestack/frontend
    ports:
    - "5173:5173"
    app:
    image: node:12-alpine
    volumes:
      - ./:/app/cached
    working_dir: /app
    ports:
      - 3000:3000
    command: npm start
    tty: true